FROM python:3.10

# Copy files with dependencies
COPY requirements.txt .

RUN pip3 install --upgrade pip

RUN pip3 install --no-cache-dir -r requirements.txt

COPY . .

CMD ["python", "manage.py", "test"]